language: ruby
rvm:
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - 1.8.7
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test